### ISSUE TITLE
Feature Request: Post messages directly into OSM's OTRS instance

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/dmca-website#1]
Currently this website sends output to an email address for the DMCA team.

This could be instead modified to open an OTRS ticket.

@grischard

**Comment by talllguy** [comment]
These could be pushed to OTRS via API (if possible) or via email. Looks like if these could go to data@openstreetmap.org, we can put a tag on the subject line so they go to the right bucket.

> Checkout Ticket Core::Ticket in the SysConfig
https://community.znuny.org/viewtopic.php?t=30728

**Comment by Firefishy** [comment]
Replaced by static site. The form gets too much abuse.
